# Generated by Django 6.0.1 on 2026-02-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_audit_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
