-- MySQL Script generated by MySQL Workbench
-- Sun Mar 24 20:54:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema locaTeka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locaTeka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locaTeka` DEFAULT CHARACTER SET utf8 ;
USE `locaTeka` ;

-- -----------------------------------------------------
-- Table `locaTeka`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locaTeka`.`table1` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
