# Generated by Django 5.0.3 on 2024-03-29 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('pt', 'Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('invited_users', models.ManyToManyField(related_name='invited_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
